# Generated by Django 5.2.9 on 2025-12-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0002_passevent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passevent',
            name='duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='passevent',
            name='visibility',
            field=models.CharField(max_length=50),
        ),
    ]
