# Generated by Django 5.2.9 on 2025-12-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0003_alter_passevent_created_at_alter_passevent_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='altitude',
            field=models.IntegerField(default=0),
        ),
    ]
