# Generated by Django 5.2.9 on 2025-12-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0004_location_altitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='passevent',
            name='direction',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='passevent',
            name='source',
            field=models.CharField(default='N2YO', max_length=50),
        ),
    ]
