# Generated by Django 5.2.9 on 2025-12-04 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.IntegerField(default=0, help_text='Altitude in meters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norad_id', models.IntegerField(unique=True, verbose_name='NORAD ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['norad_id'],
            },
        ),
        migrations.CreateModel(
            name='PassPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_elevation', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Max Elevation (°)')),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('visibility', models.CharField(choices=[('V', 'Visible'), ('D', 'Daylight'), ('N', 'Night')], max_length=1)),
                ('start_azimuth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_azimuth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('end_azimuth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('magnitude', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='heavens-above', max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='tracker.location')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='tracker.satellite')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='tracker_pas_start_t_63301e_idx'), models.Index(fields=['location', 'satellite'], name='tracker_pas_locatio_bc812a_idx')],
            },
        ),
    ]
